version: '3.5'
services:
  omar-web-proxy-app:
    image: quay.io/radiantsolutions/omar-web-proxy-app:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./apache-selfsigned.crt:/etc/ssl/server-certs/server.pem
      - ./apache-selfsigned.key:/etc/ssl/server-certs/server.key
      - ./reverse-proxy.conf:/etc/httpd/conf.d/reverse-proxy.conf
    networks:
      - proxynet

networks:
  proxynet:
    name: proxynet

