version: '3.5'
services:
#  nginx:
#    image: nginx:latest
#    ports:
#      - 80:80
#    volumes:
#      - ./nginx.conf:/etc/nginx/conf.d/default.conf
#    networks:
#      - proxynet

  omar-web-proxy-app:
    image: quay.io/radiantsolutions/omar-web-proxy-app:latest
    ports:
      - 80:80
    volumes:
      - ./reverse-proxy.conf:/etc/httpd/conf.d/reverse-proxy.conf
    networks:
      - proxynet

networks:
  proxynet:
    name: proxynet

