version: '3.5'
services:
  omar-config-server:
    image: ${DOCKER_URL}/omar-config-server:${OMAR_CONFIG_SERVER_VERSION}
    env_file:
      - envs/omar-config-server.env
    volumes:
      - ./spring-configs:/home/omar/configs
    networks:
      - proxynet
      - omarnet

  omar-eureka-server:
    image: ${DOCKER_URL}/omar-eureka-server:${OMAR_EUREKA_SERVER_VERSION}
    env_file:
      - envs/omar-eureka-server.env
    networks:
      - proxynet
      - omarnet

  nifi:
    image: ${DOCKER_URL}/nifi:${OMAR_NIFI_VERSION}
    env_file:
      - envs/nifi.env
    networks:
      - proxynet
      - omarnet

  omar-admin-server:
    image: ${DOCKER_URL}/omar-admin-server:${OMAR_ADMIN_SERVER_VERSION}
    env_file:
      - envs/omar-admin-server.env
    networks:
      - proxynet
      - omarnet

  omar-disk-cleanup-app:
    image: ${DOCKER_URL}/omar-disk-cleanup-app:${OMAR_DISK_CLEANUP_VERSION}
    env_file:
      - envs/omar-disk-cleanup-app.env
    networks:
      - proxynet
      - omarnet

  omar-download-app:
    image: ${DOCKER_URL}/omar-download-app:${OMAR_DOWNLOAD_APP_VERSION}
    env_file:
      - envs/omar-download-app.env
    volumes:
      - data_path:/data
    networks:
      - proxynet
      - omarnet

  omar-geoscript-app:
    image: ${DOCKER_URL}/omar-geoscript-app:${OMAR_GEOSCRIPT_APP_VERSION}
    env_file:
      - envs/omar-geoscript-app.env
    networks:
      - proxynet
      - omarnet

  omar-mensa-app:
    image: ${DOCKER_URL}/omar-mensa-app:${OMAR_MENSA_APP_VERSION}
    env_file:
      - envs/omar-mensa-app.env
    volumes:
      - data_path:/data
    networks:
      - proxynet
      - omarnet

  omar-ml:
    image: ${DOCKER_URL}/omar-ml:${OMAR_ML_VERSION}
    env_file:
      - envs/omar-ml.env
    networks:
      - proxynet
      - omarnet

  omar-oms-app:
    image: ${DOCKER_URL}/omar-oms-app:${OMAR_OMS_APP_VERSION}
    env_file:
      - envs/omar-oms-app.env
    volumes:
      - data_path:/data
    networks:
      - proxynet
      - omarnet

  omar-services-monitor-app:
    image: ${DOCKER_URL}/omar-services-monitor-app:${OMAR_SERVICES_MONITOR_VERSION}
    env_file:
      - envs/omar-services-monitor-app.env
    networks:
      - proxynet
      - omarnet

  omar-stager-app:
    image: ${DOCKER_URL}/omar-stager-app:${OMAR_STAGER_APP_VERSION}
    env_file:
      - envs/omar-stager-app.env
    volumes:
      - data_path:/data
    networks:
      - proxynet
      - omarnet

  omar-superoverlay-app:
    image: ${DOCKER_URL}/omar-superoverlay-app:${OMAR_SUPEROVERLAY_APP_VERSION}
    env_file:
      - envs/omar-superoverlay-app.env
    networks:
      - proxynet
      - omarnet

  omar-twofishes:
    image: ${DOCKER_URL}/omar-twofishes:${OMAR_TWOFISHES_VERSION}
    env_file:
      - envs/omar-twofishes.env
    networks:
      - proxynet
      - omarnet

  omar-upload-app:
    image: ${DOCKER_URL}/omar-upload-app:${OMAR_UPLOAD_APP_VERSION}
    env_file:
      - envs/omar-upload-app.env
    volumes:
      - data_path:/data
    networks:
      - proxynet
      - omarnet

  omar-wcs-app:
    image: ${DOCKER_URL}/omar-wcs-app:${OMAR_WCS_APP_VERSION}
    env_file:
      - envs/omar-wcs-app.env
    networks:
      - proxynet
      - omarnet

  omar-wfs-app:
    image: ${DOCKER_URL}/omar-wfs-app:${OMAR_WFS_APP_VERSION}
    env_file:
      - envs/omar-wfs-app.env
    networks:
      - proxynet
      - omarnet

  omar-wms-app:
    image: ${DOCKER_URL}/omar-wms-app:${OMAR_WMS_APP_VERSION}
    env_file:
      - envs/omar-wms-app.env
    networks:
      - proxynet
      - omarnet

  omar-wmts-app:
    image: ${DOCKER_URL}/omar-wmts-app:${OMAR_WMTS_APP_VERSION}
    env_file:
      - envs/omar-wmts-app.env
    networks:
      - proxynet
      - omarnet

  rabbitmq:
    image: ${DOCKER_URL}/rabbitmq:${RABBITMQ_VERSION}
    env_file:
      - envs/rabbitmq.env
    networks:
      - proxynet
      - omarnet

  tlv-app:
    image: ${DOCKER_URL}/tlv-app:${TLV_APP_VERSION}
    env_file:
      - envs/tlv-app.env
    networks:
      - proxynet
      - omarnet

  omar-ui-app:
    image: ${DOCKER_URL}/omar-ui-app:${OMAR_UI_APP_VERSION}
    env_file:
      - envs/omar-ui-app.env
    networks:
      - proxynet
      - omarnet

  omar-basemap:
    image: ${DOCKER_URL}/omar-basemap:${OMAR_BASEMAP_VERSION}
    networks:
      - proxynet
      - omarnet

  omar-mapproxy:
    image: ${DOCKER_URL}/omar-mapproxy:${OMAR_MAPPROXY_VERSION}
    networks:
      - proxynet
      - omarnet

  omar-postgres:
    image: ${DOCKER_URL}/postgres-postgis-trgm:${OMAR_POSTGRES_VERSION}
    env_file:
      - envs/omar-postgres.env
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
    networks:
      - proxynet
      - omarnet

networks:
  proxynet:
    name: proxynet
  omarnet:
    external: false

volumes:
  data_path:
    driver: local
    driver_opts:
      type: bind
      devices: /data
  pgdata:
    driver: local
    driver_opts:
      type: bind
      devices: ./pgdata