---
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  labels:
    k8s-app: filebeat-es-cluster
data:
  filebeat.yml: |-
    filebeat.config:
      prospectors:
        # Mounted `filebeat-prospectors` configmap:
        path: ${path.config}/prospectors.d/*.yml
        # Reload prospectors configs as they change:
        reload.enabled: false

      modules:
        path: ${path.config}/modules.d/*.yml
        # Reload module configs as they change:
        reload.enabled: false

    processors:
      - add_cloud_metadata: ~
    setup.template.name: "o2-filebeat"
    setup.template.pattern: "o2-filebeat-*"
    setup.template.overwrite: false
    setup.template.enabled: true
    cloud.id: ${ELASTIC_CLOUD_ID}
    cloud.auth: ${ELASTIC_CLOUD_AUTH}
    output.elasticsearch:
      hosts: ['https://kibana.PROJECT_NAMESPACE.svc.cluster.local:9200']
      username: ${ELASTICSEARCH_USERNAME}
      password: ${ELASTICSEARCH_PASSWORD}
      index: "o2-filebeat-default-%{[beat.version]}-%{+yyyy.MM.dd}"
      indices:
        - index: "o2-filebeat-%{[kubernetes.namespace]}-%{[beat.version]}-%{+yyyy.MM.dd}"
          when.regexp:
            kubernetes.namespace: ".*"
      ssl:
        verification_mode: none
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-prospectors
  labels:
    k8s-app: filebeat-es-cluster
data:
  kubernetes.yml: |-
    - type: docker
      containers.ids:
      - "*"
      exclude_lines: ['Error decoding JSON']
      json.keys_under_root: true
      json.overwrite_keys: true
      json.ignore_decoding_error: true
      json.add_error_key: false
      json.message_key: message
      processors:
        - add_kubernetes_metadata:
            in_cluster: true
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: filebeat-es-cluster
  labels:
    k8s-app: filebeat-es-cluster
spec:
  selector:
    matchLabels:
      name: filebeat-daemonset
  template:
    metadata:
      labels:
        name: filebeat-daemonset
    spec:
      nodeSelector:
        node-role.kubernetes.io/compute: "true"
      serviceAccountName: filebeat-es-cluster
      terminationGracePeriodSeconds: 10
      containers:
      - name: filebeat
        image: docker-registry.default.svc:5000/PROJECT_NAMESPACE/filebeat:6.5.2
        args: [
          "-c", "/etc/filebeat.yml",
          "-e",
        ]
        env:
        - name: ELASTICSEARCH_HOST
          value: https://kibana.PROJECT_NAMESPACE.endpoints.cluster.local:9200
        - name: ELASTICSEARCH_PORT
          value: "9200"
        - name: ELASTICSEARCH_USERNAME
          value: ES_USERNAME
        - name: ELASTICSEARCH_PASSWORD
          value: ES_PASSWORD
        securityContext:
          runAsUser: 0
          privileged: true
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - name: config
          mountPath: /etc/filebeat.yml
          readOnly: true
          subPath: filebeat.yml
        - name: prospectors
          mountPath: /usr/share/filebeat/prospectors.d
          readOnly: true
        - name: data
          mountPath: /usr/share/filebeat/data
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      volumes:
      - name: config
        configMap:
          defaultMode: 0600
          name: filebeat-config
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: prospectors
        configMap:
          defaultMode: 0600
          name: filebeat-prospectors
      - name: data
        emptyDir: {}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: filebeat-es-cluster
subjects:
- kind: ServiceAccount
  name: filebeat-es-cluster
  namespace: PROJECT_NAMESPACE
roleRef:
  kind: ClusterRole
  name: filebeat-es-cluster
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: filebeat-es-cluster
  labels:
    k8s-app: filebeat-es-cluster
rules:
- apiGroups: [""] # "" indicates the core API group
  resources:
  - namespaces
  - pods
  verbs:
  - get
  - watch
  - list
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: filebeat-es-cluster
  labels:
    k8s-app: filebeat-es-cluster
---